stream: stream.hs
	ghc -dynamic stream.hs
	./stream
	rm stream stream.hi stream.o

pair: pair.hs
	ghc -dynamic pair.hs
	./pair
	rm pair pair.hi pair.o

adjunction: adjunction.hs
	ghc -dynamic adjunction.hs
	./adjunction
	rm adjunction adjunction.hi adjunction.o

question: question.hs
	ghc -dynamic question.hs
	./question
	rm question question.hi question.o
